### ISSUE TITLE
Metric paths truncated when prefix not provided

### ISSUE THREAD

**Issue by noslowerdna** [BrightcoveOS/metrics-graphite-pickle#3]
If a metric prefix is not provided for the GraphitePickleReporter, the valueName part of the metric is not included in the PyTuple constructed in addMetric(...).  This results in truncated metric paths missing the final .mean, .stddev, etc.

**Comment by samperman** [comment]
Thanks for the pointing that out. I just pushed a snapshot (metrics-graphite-pickle-1.0.5-SNAPSHOT) that should be available soon if you want to give it a go. I'll release that sometime this week.

**Comment by samperman** [comment]
Actually... i just went ahead and released. version 1.0.5 should be available in maven central in a couple hours.
