### ISSUE TITLE
Not able to write metrics into graphite with GraphitePickleReporter.

### ISSUE THREAD

**Issue by vijayakumar** [BrightcoveOS/metrics-graphite-pickle#6]
For some reason, metrics are not getting written to graphite (when using GraphitePickleReporter but when I change the class to GraphiteReporter it works). I could see run() method getting executed & no exceptions are thrown.

Here is my dependency list:
metrics-core-2.1.3.jar  
metrics-graphite-2.2.0.jar  
metrics-graphite-pickle-1.1.0.jar
jython-standalone-2.5.3.jar.

Am I missing anything else?

Thanks,
Vijayakumar.

**Comment by samperman** [comment]
Can you try metrics-core-2.2.0? I don't know why that would make a difference... Does sending metrics using pickle work from normal python apps?

**Comment by samperman** [comment]
Reopen if this is still an issue.
